# This file contains the fastlane.tools configuration
# for the Android release build.
# You can find the documentation at https://docs.fastlane.tools

# Load the shared native app properties.
require('dotenv')
Dotenv.load '../../Skip.env'

default_platform(:android)

# Use the Homebrew gradle rather than expecting a local gradlew.
gradle_bin = (ENV['HOMEBREW_PREFIX'] ? ENV['HOMEBREW_PREFIX'] : "/opt/homebrew") + "/bin/gradle"

desc "Build Conclave Android app"
lane :build do |options|
  build_config = (options[:release] ? "Release" : "Debug")
  gradle(
    task: "assemble#{build_config}",
    gradle_path: gradle_bin,
    flags: "--warning-mode none -x lint"
  )
end

desc "Test Conclave Android app"
lane :test do
  gradle(
    task: "test",
    gradle_path: gradle_bin
  )
end

desc "Assemble Conclave Android release bundle"
lane :assemble do
  gradle(
    gradle_path: gradle_bin,
    task: "bundleRelease"
  )
end

desc "Deploy Conclave Android app to Google Play"
lane :release do

  assemble

  upload_to_play_store(
    aab: '../.build/Android/app/outputs/bundle/release/app-release.aab'
  )
end
