import SwiftUI
import Observation
#if canImport(UIKit) && !SKIP
import UIKit
#endif

#if SKIP
// Carbon palette bridge for native Material3 controls generated by Skip.
private func acmM3(_ r: Double, _ g: Double, _ b: Double, _ a: Double = 1.0) -> androidx.compose.ui.graphics.Color {
    androidx.compose.ui.graphics.Color(
        red: Float(r / 255.0),
        green: Float(g / 255.0),
        blue: Float(b / 255.0),
        alpha: Float(a)
    )
}
#endif

struct ContentView: View {
    @Bindable var appState: AppState
    // Keep meetings alive across backgrounding, Activity recreation, and PiP swaps.
    @State private var meetingViewModel = MeetingViewModel.shared
    @State private var pendingJoinPromptRequestID: Int?

    var body: some View {
        Group {
            switch meetingViewModel.state.connectionState {
            case .disconnected, .connecting, .connected:
                JoinView(viewModel: meetingViewModel, appState: appState)
                    .transition(.opacity)

            case .joining, .joined, .reconnecting:
                MeetingView(viewModel: meetingViewModel)
                    .transition(.opacity)

            case .waiting:
                WaitingRoomView(viewModel: meetingViewModel)
                    .transition(.opacity)

            case .error:
                ErrorView(
                    message: meetingViewModel.state.errorMessage ?? "An error occurred",
                    onRetry: { meetingViewModel.resetError() }
                )
                .transition(.opacity)
            }
        }
        .overlay {
            pendingJoinPromptOverlay
        }
        .onAppear {
            handlePendingJoinURLIfNeeded()
        }
        .onChange(of: appState.pendingJoinRequestID) { _, _ in
            handlePendingJoinURLIfNeeded()
        }
        .onChange(of: meetingViewModel.state.connectionState) { _, _ in
            handlePendingJoinURLIfNeeded()
        }
        .animation(.easeInOut(duration: 0.3), value: meetingViewModel.state.connectionState)
        .preferredColorScheme(.dark)
        .tint(ACMColors.primaryOrange)
        #if SKIP
        .material3ColorScheme { scheme, _ in
            scheme.copy(
                primary: acmM3(249, 95, 74),
                onPrimary: acmM3(255, 255, 255),
                primaryContainer: acmM3(249, 95, 74),
                onPrimaryContainer: acmM3(255, 255, 255),
                secondary: acmM3(255, 0, 122),
                onSecondary: acmM3(255, 255, 255),
                background: acmM3(10, 10, 11),
                onBackground: acmM3(250, 250, 250),
                surface: acmM3(24, 24, 27),
                onSurface: acmM3(250, 250, 250),
                surfaceVariant: acmM3(35, 35, 39),
                onSurfaceVariant: acmM3(250, 250, 250, 0.74),
                error: acmM3(234, 67, 53),
                onError: acmM3(255, 255, 255),
                outline: acmM3(250, 250, 250, 0.24),
                outlineVariant: acmM3(250, 250, 250, 0.14),
                surfaceContainerLowest: acmM3(10, 10, 11),
                surfaceContainerLow: acmM3(19, 19, 22),
                surfaceContainer: acmM3(24, 24, 27),
                surfaceContainerHigh: acmM3(35, 35, 39),
                surfaceContainerHighest: acmM3(46, 46, 51),
                scrim: acmM3(0, 0, 0)
            )
        }
        #endif
    }

    @ViewBuilder
    private var pendingJoinPromptOverlay: some View {
        if pendingJoinPromptRequestID != nil,
           appState.pendingJoinURLString != nil,
           isInMeetingSession {
            ZStack {
                Color.black.opacity(0.74)
                    .ignoresSafeArea()

                VStack(alignment: .leading, spacing: 16) {
                    VStack(alignment: .leading, spacing: 6) {
                        Text("Join new meeting?")
                            .font(ACMFont.trial(18, weight: .bold))
                            .foregroundStyle(ACMColors.text)

                        Text("You are currently in \(currentRoomLabel). Leave it and join \(pendingJoinRoomLabel)?")
                            .font(ACMFont.trial(13))
                            .foregroundStyle(ACMColors.textMuted)
                    }

                    HStack(spacing: 10) {
                        Spacer()

                        Button {
                            dismissPendingJoinPrompt()
                        } label: {
                            Text("Stay")
                                .font(ACMFont.trial(12, weight: .semibold))
                                .textCase(.uppercase)
                                .foregroundStyle(ACMColors.textMuted)
                                .padding(.horizontal, 14)
                                .frame(height: 38)
                                .overlay {
                                    RoundedRectangle(cornerRadius: ACMRadius.sm)
                                        .strokeBorder(ACMColors.border, lineWidth: 1.0)
                                }
                        }
                        .buttonStyle(.plain)

                        Button {
                            acceptPendingJoinPrompt()
                        } label: {
                            Text("Leave & Join")
                                .font(ACMFont.trial(12, weight: .semibold))
                                .textCase(.uppercase)
                                .foregroundStyle(.white)
                                .padding(.horizontal, 14)
                                .frame(height: 38)
                                .acmColorBackground(ACMColors.primaryOrange)
                                .clipShape(RoundedRectangle(cornerRadius: ACMRadius.sm))
                        }
                        .buttonStyle(.plain)
                    }
                }
                .padding(20)
                .frame(maxWidth: 360)
                .acmGlassRoundedRect(cornerRadius: ACMRadius.lg)
                .padding(.horizontal, 24)
            }
            .transition(.opacity)
        }
    }

    private var isInMeetingSession: Bool {
        switch meetingViewModel.state.connectionState {
        case .joining, .joined, .reconnecting, .waiting:
            return true
        case .disconnected, .connecting, .connected, .error:
            return false
        }
    }

    private var currentRoomLabel: String {
        let roomId = meetingViewModel.state.roomId.trimmingCharacters(in: .whitespacesAndNewlines)
        return roomId.isEmpty ? "your current meeting" : roomId
    }

    private var pendingJoinRoomLabel: String {
        guard let link = appState.pendingJoinURLString,
              let roomId = roomIdFromJoinURLString(link),
              !roomId.isEmpty else {
            return "another meeting"
        }
        return roomId
    }

    private func handlePendingJoinURLIfNeeded() {
        guard let pendingURL = appState.pendingJoinURLString else {
            pendingJoinPromptRequestID = nil
            return
        }

        guard let pendingRoomId = roomIdFromJoinURLString(pendingURL),
              !pendingRoomId.isEmpty else {
            _ = appState.consumePendingJoinURLString()
            pendingJoinPromptRequestID = nil
            return
        }

        if meetingViewModel.state.connectionState == .error {
            pendingJoinPromptRequestID = nil
            meetingViewModel.resetError()
            return
        }

        guard isInMeetingSession else {
            pendingJoinPromptRequestID = nil
            return
        }

        if meetingViewModel.isCurrentRoomDeepLinkTarget(pendingRoomId) {
            _ = appState.consumePendingJoinURLString()
            pendingJoinPromptRequestID = nil
            return
        }

        pendingJoinPromptRequestID = appState.pendingJoinRequestID
    }

    private func dismissPendingJoinPrompt() {
        _ = appState.consumePendingJoinURLString()
        pendingJoinPromptRequestID = nil
    }

    private func acceptPendingJoinPrompt() {
        guard appState.pendingJoinURLString != nil else {
            pendingJoinPromptRequestID = nil
            return
        }
        pendingJoinPromptRequestID = nil
        meetingViewModel.leaveRoom()
    }

    private func roomIdFromJoinURLString(_ input: String) -> String? {
        let trimmed = input.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        let normalized = normalizeJoinURLString(trimmed)
        if hasURLScheme(normalized) {
            guard let components = URLComponents(string: normalized),
                  isSupportedJoinURLScheme(components.scheme) else { return nil }
            let segments = joinPathSegments(from: components)
            guard !isWebOnlyConclavePath(components: components, segments: segments) else { return nil }
            return roomId(fromPathSegments: segments)
        }

        let parts = trimmed.split(separator: "?", maxSplits: 1, omittingEmptySubsequences: false)
        let path = parts.isEmpty ? trimmed : String(parts[0])
        if path.contains("/") {
            let segments = pathSegments(from: path)
            if let roomId = roomId(fromPathSegments: segments) {
                return roomId
            }
        }

        let sanitized = sanitizeRoomCode(path)
        return sanitized.isEmpty ? nil : sanitized
    }

    private func normalizeJoinURLString(_ input: String) -> String {
        let lowercased = input.lowercased()
        if lowercased.hasPrefix("conclave.acmvit.in") || lowercased.hasPrefix("www.conclave.acmvit.in") {
            return "https://\(input)"
        }
        if isLocalConclaveWebHostWithoutScheme(lowercased) {
            return "http://\(input)"
        }
        return input
    }

    private func isLocalConclaveWebHostWithoutScheme(_ input: String) -> Bool {
        let authority = joinURLAuthorityPrefix(in: input)
        let host: String
        if authority.hasPrefix("["),
           let closingBracketIndex = authority.firstIndex(of: "]") {
            host = String(authority[...closingBracketIndex])
        } else if let colonIndex = authority.firstIndex(of: ":") {
            host = String(authority[..<colonIndex])
        } else {
            host = authority
        }
        return localConclaveWebHosts.contains(host)
    }

    private func joinURLAuthorityPrefix(in input: String) -> String {
        var authority = ""
        for character in input {
            if character == "/" || character == "?" || character == "#" {
                break
            }
            authority += String(character)
        }
        return authority
    }

    private func hasURLScheme(_ input: String) -> Bool {
        guard let colonIndex = input.firstIndex(of: ":") else { return false }
        let scheme = String(input[..<colonIndex])
        guard let first = scheme.first else { return false }
        let letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
        let allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+.-"
        guard letters.contains(first) else { return false }
        for character in scheme where !allowed.contains(character) {
            return false
        }
        return true
    }

    private func isSupportedJoinURLScheme(_ scheme: String?) -> Bool {
        switch scheme?.lowercased() {
        case "http", "https", "conclave":
            return true
        default:
            return false
        }
    }

    private func joinPathSegments(from components: URLComponents) -> [String] {
        var segments = pathSegments(from: components.path)
        if components.scheme?.lowercased() == "conclave",
           let host = components.host,
           !host.isEmpty {
            segments.insert(host, at: 0)
        }
        return segments
    }

    private func pathSegments(from path: String) -> [String] {
        var segments: [String] = []
        for segment in path.split(separator: "/", omittingEmptySubsequences: true) {
            segments.append(String(segment))
        }
        return segments
    }

    private func roomId(fromPathSegments segments: [String]) -> String? {
        guard !segments.isEmpty else { return nil }
        if segments.count >= 2 && segments[0].lowercased() == "w" {
            let roomId = sanitizeWebinarLinkCode(segments[1])
            return roomId.isEmpty ? nil : roomId
        }
        guard let rawRoomId = segments.last else { return nil }
        let roomId = sanitizeRoomCode(rawRoomId)
        return roomId.isEmpty ? nil : roomId
    }

    private func isWebOnlyConclavePath(components: URLComponents, segments: [String]) -> Bool {
        guard let scheme = components.scheme?.lowercased(),
              scheme == "http" || scheme == "https",
              isConclaveWebHost(components.host),
              let firstSegment = segments.first?.lowercased() else {
            return false
        }

        if firstSegment.contains(".") {
            return true
        }

        return webOnlyConclavePathPrefixes.contains(firstSegment)
    }

    private func isConclaveWebHost(_ host: String?) -> Bool {
        let normalized = host?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() ?? ""
        return normalized == "conclave.acmvit.in" ||
            normalized == "www.conclave.acmvit.in" ||
            localConclaveWebHosts.contains(normalized)
    }

    private func sanitizeRoomCode(_ value: String) -> String {
        let normalized = normalizeRoomCharacters(in: value)
        return String(normalized.prefix(64))
    }

    private func sanitizeWebinarLinkCode(_ value: String) -> String {
        let allowed = "abcdefghijklmnopqrstuvwxyz0123456789-"
        var sanitized = ""
        for character in value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
            if allowed.contains(character) {
                sanitized += String(character)
                if sanitized.count >= 32 {
                    break
                }
            }
        }
        return sanitized
    }

    private func normalizeRoomCharacters(in input: String) -> String {
        let separator: Character = "-"
        var normalized = ""
        var previousWasSeparator = false
        let allowed = "abcdefghijklmnopqrstuvwxyz0123456789"

        for character in input.lowercased() {
            if allowed.contains(character) {
                normalized += String(character)
                previousWasSeparator = false
            } else if !normalized.isEmpty && !previousWasSeparator {
                normalized += String(separator)
                previousWasSeparator = true
            }
        }

        if previousWasSeparator && !normalized.isEmpty {
            normalized = String(normalized.dropLast())
        }
        return normalized
    }

    private let webOnlyConclavePathPrefixes: Set<String> = [
        "_next",
        "api",
        "assets",
        "effects",
        "mediapipe",
        "reactions",
        "workers",
        "delete-account",
        "privacy",
        "sfu-admin",
        "sign-in"
    ]
    private let localConclaveWebHosts: Set<String> = {
        var hosts: Set<String> = [
            "localhost",
            "127.0.0.1",
            "0.0.0.0",
            "[::1]",
            "::1"
        ]
        #if DEBUG
        hosts.insert(SfuJoinService.androidEmulatorLoopbackHost())
        #endif
        return hosts
    }()
}

// MARK: - Waiting Room View

struct WaitingRoomView: View {
    @Bindable var viewModel: MeetingViewModel

    private var waitingMessage: String? {
        let message = viewModel.state.waitingMessage?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return message.isEmpty ? nil : message
    }

    private var waitingTitle: String {
        waitingMessage ?? "Waiting for host to let you in"
    }

    private var waitingIntro: String {
        guard let waitingMessage else {
            return "Hang tight."
        }

        if waitingMessage.lowercased().contains("locked") {
            return "Please wait while the host reviews your request."
        }

        return "The host left the room, so there is no one available to admit you right now."
    }

    var body: some View {
        ZStack {
            ACMColors.dark
                .ignoresSafeArea()

            GeometryReader { geometry in
#if !SKIP
                Canvas { context, size in
                    let spacing: CGFloat = 30
                    let dotSize: CGFloat = 1.5

                    for x in stride(from: 0, to: size.width, by: spacing) {
                        for y in stride(from: 0, to: size.height, by: spacing) {
                            let rect = CGRect(
                                x: x - dotSize / 2,
                                y: y - dotSize / 2,
                                width: dotSize,
                                height: dotSize
                            )
                            context.fill(
                                Path(ellipseIn: rect),
                                with: GraphicsContext.Shading.color(ACMColors.creamGhost)
                            )
                        }
                    }
                }
#else
                Color.clear
#endif
            }
            .ignoresSafeArea()

            VStack(spacing: ACMSpacing.xl) {
                ZStack {
                    Circle()
                        .stroke(ACMColors.primaryOrangeGhost, lineWidth: 3.0)
                        .frame(width: 80.0, height: 80.0)

#if SKIP
                    ProgressView()
                        .progressViewStyle(.circular)
                        .tint(ACMColors.primaryOrange)
#else
                    Circle()
                        .trim(from: 0.0, to: 0.7)
                        .stroke(ACMColors.primaryOrange, style: StrokeStyle(lineWidth: 3.0, lineCap: .round))
                        .frame(width: 80.0, height: 80.0)
                        .rotationEffect(Angle.degrees(-90))
                        .modifier(RotatingModifier())
#endif
                }

                VStack(spacing: ACMSpacing.xs) {
                    Text(waitingTitle)
                        .font(ACMFont.trial(24, weight: .bold))
                        .foregroundStyle(ACMColors.text)
                        .multilineTextAlignment(.center)

                    Text(waitingIntro)
                        .font(ACMFont.trial(14))
                        .foregroundStyle(ACMColors.textMuted)
                        .multilineTextAlignment(.center)
                }

                Button {
                    MeetingShare.copyMeetingLink(viewModel.state.meetingLink)
                } label: {
                    Text(viewModel.state.roomId)
                        .font(ACMFont.trial(14, weight: .medium))
                        .foregroundStyle(ACMColors.text)
                        .padding(.horizontal, ACMSpacing.md)
                        .padding(.vertical, 10)
                        .acmColorBackground(ACMColors.surface)
                        .overlay {
                            RoundedRectangle(cornerRadius: ACMRadius.sm)
                                .strokeBorder(ACMColors.border, lineWidth: 1.0)
                        }
                        .clipShape(RoundedRectangle(cornerRadius: ACMRadius.sm))
                }
                .buttonStyle(.plain)

                Button {
                    viewModel.leaveRoom()
                } label: {
                    Text("Cancel")
                        .font(ACMFont.trial(16, weight: .medium))
                        .foregroundStyle(ACMColors.textMuted)
                        .frame(maxWidth: .infinity)
                        .frame(height: 54.0)
                        .overlay {
                            RoundedRectangle(cornerRadius: ACMRadius.lg)
                                .strokeBorder(ACMColors.border, lineWidth: 1.0)
                        }
                }
                .frame(maxWidth: 280)
                .padding(.top, ACMSpacing.xs)
            }
            .padding(ACMSpacing.xl)
        }
    }
}

struct RotatingModifier: ViewModifier {
    @State private var isRotating = false

    func body(content: Content) -> some View {
        content
            .rotationEffect(.degrees(isRotating ? 360.0 : 0.0))
            .animation(.linear(duration: 1).repeatForever(autoreverses: false), value: isRotating)
            .onAppear {
                isRotating = true
            }
    }
}

// MARK: - Error View

struct ErrorView: View {
    let message: String
    let onRetry: () -> Void

    var body: some View {
        ZStack {
            ACMColors.dark
                .ignoresSafeArea()

            VStack(spacing: ACMSpacing.xl) {
                ZStack {
                    Circle()
                        .fill(ACMColors.error.opacity(0.12))
                        .frame(width: 80.0, height: 80.0)

                    ACMSystemIcon.icon("exclamationmark.triangle.fill", android: "warning", size: 32, tint: "danger")
                        .foregroundStyle(ACMColors.error)
                }

                VStack(spacing: ACMSpacing.xs) {
                    Text("Something went wrong")
                        .font(ACMFont.trial(22, weight: .bold))
                        .foregroundStyle(ACMColors.text)

                    Text(message)
                        .font(ACMFont.trial(14))
                        .foregroundStyle(ACMColors.textMuted)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: 280)
                }

                Button(action: onRetry) {
                    Text("Try again")
                        .font(ACMFont.trial(16, weight: .medium))
                        .foregroundStyle(Color.white)
                        .frame(maxWidth: .infinity)
                        .frame(height: 54.0)
                        .acmColorBackground(ACMColors.primaryOrange)
                        .clipShape(RoundedRectangle(cornerRadius: ACMRadius.lg))
                }
                .frame(maxWidth: 280)
            }
            .padding(ACMSpacing.xl)
        }
    }
}

#Preview {
    ContentView(appState: AppState())
}
