const GHOST_MODE_EMAILS: Record<string, true> = {
  "aakanksha.singh2024@vitstudent.ac.in": true,
  "aardra.sindhunair2024@vitstudent.ac.in": true,
  "aarav.gupta2024@vitstudent.ac.in": true,
  "aarjav.jain2023@vitstudent.ac.in": true,
  "aarjavjain.acmvit@gmail.com": true,
  "aasasingh.bhui2023@vitstudent.ac.in": true,
  "aayush.dwivedi2024@vitstudent.ac.in": true,
  "abhyuday.rai2024@vitstudent.ac.in": true,
  "acm@vit.ac.in": true,
  "adheesh.garg2023@vitstudent.ac.in": true,
  "adhyan.jain2024@vitstudent.ac.in": true,
  "aditya.naik2022@vitstudent.ac.in": true,
  "aditya.singh2023f@vitstudent.ac.in": true,
  "aditya.vardhan2024@vitstudent.ac.in": true,
  "ajinkya.phatak2023@vitstudent.ac.in": true,
  "ananya.bisht2024@vitstudent.ac.in": true,
  "ananya.sahu2024@vitstudent.ac.in": true,
  "anish.agarwal2024@vitstudent.ac.in": true,
  "anshul.sandeep2023@vitstudent.ac.in": true,
  "aribam.tamanna2024@vitstudent.ac.in": true,
  "archit.nigam2024@vitstudent.ac.in": true,
  "arnav.singh2024@vitstudent.ac.in": true,
  "arnav.soni2024@vitstudent.ac.in": true,
  "ashman.singh2024@vitstudent.ac.in": true,
  "ashmansingha158w@gmail.com": true,
  "atharva.narendra2024@vitstudent.ac.in": true,
  "bhanu.maheshchekuri2024@vitstudent.ac.in": true,
  "chinmayee.mallappa2024@vitstudent.ac.in": true,
  "chitransh.saxena2023@vitstudent.ac.in": true,
  "dev.jain2023@vitstudent.ac.in": true,
  "devipriya.rprakash2024@vitstudent.ac.in": true,
  "dherya.jain2024@vitstudent.ac.in": true,
  "divyam.agrawal2024@vitstudent.ac.in": true,
  "drashti.shukla2023@vitstudent.ac.in": true,
  "drashtishukla1320@gmail.com": true,
  "eshita.chokhani2022@vitstudent.ac.in": true,
  "garuda.ramkiran2024@vitstudent.ac.in": true,
  "garv.jain2022a@vitstudent.ac.in": true,
  "harikrishna.v2024@vitstudent.ac.in": true,
  "harshit.narang2023@vitstudent.ac.in": true,
  "harshit.vootukuri2022@vitstudent.ac.in": true,
  "harshitnarang289@gmail.com": true,
  "hazel.mbenny2024@vitstudent.ac.in": true,
  "hemanth.balgi2022@vitstudent.ac.in": true,
  "hemanth.shivanand2022@vitstudent.ac.in": true,
  "ishaan.deepak2023@vitstudent.ac.in": true,
  "ishaan.shrivastava2024a@vitstudent.ac.in": true,
  "ishhan.kheria2024@vitstudent.ac.in": true,
  "ishita.joshi2024@vitstudent.ac.in": true,
  "jahnavi.singh2024@vitstudent.ac.in": true,
  "jennifer.sangeetha2024@vitstudent.ac.in": true,
  "jjoshiprakhar@gmail.com": true,
  "kairavnitin.sheth2022@vitstudent.ac.in": true,
  "kareliya.meet2024@vitstudent.ac.in": true,
  "kishen.pathiyan2024@vitstudent.ac.in": true,
  "krishang.zinzuwadia2024@vitstudent.ac.in": true,
  "krishangzinzuwadia@gmail.com": true,
  "krishika.sureka2023@vitstudent.ac.in": true,
  "lakshita.ajmera2024@vitstudent.ac.in": true,
  "lavanya.jain2023@vitstudent.ac.in": true,
  "lavanyajain.acmvit@gmail.com": true,
  "mahendra.sajjan2023@vitstudent.ac.in": true,
  "mahendrac482@gmail.com": true,
  "maitri.shah2024@vitstudent.ac.in": true,
  "manan.shah2022@vitstudent.ac.in": true,
  "myselfshaurya17@gmail.com": true,
  "nakul.sinha2024@vitstudent.ac.in": true,
  "navaneeth.krishna2024@vitstudent.ac.in": true,
  "navdha.sharma2023@vitstudent.ac.in": true,
  "navdhasharma02@gmail.com": true,
  "nimesha.subramanian2024@vitstudent.ac.in": true,
  "nishtha.aggarwal2023@vitstudent.ac.in": true,
  "nishthaagarwal248@gmail.com": true,
  "nitu.su2024@vitstudent.ac.in": true,
  "pakhi.mittal2024@vitstudent.ac.in": true,
  "parneeca.prasad2024@vitstudent.ac.in": true,
  "prakhar.joshi2023@vitstudent.ac.in": true,
  "pritha.sharma2024@vitstudent.ac.in": true,
  "prithvi.raghu2024@vitstudent.ac.in": true,
  "prithviraghu080706@gmail.com": true,
  "rachel.patni2024@vitstudent.ac.in": true,
  "ridwicklingan.t2024@vitstudent.ac.in": true,
  "rishika.gupta2024@vitstudent.ac.in": true,
  "rishit.shivam2023@vitstudent.ac.in": true,
  "rishitshivam@gmail.com": true,
  "rithik.meedinti2023@vitstudent.ac.in": true,
  "rohit.phaniram2023@vitstudent.ac.in": true,
  "rohitsakamuri@gmail.com": true,
  "saharsh.bhansali2021@vitstudent.ac.in": true,
  "saiyam.kalra2024@vitstudent.ac.in": true,
  "samarth.manojnaik2024@vitstudent.ac.in": true,
  "samrat.singh2024@vitstudent.ac.in": true,
  "sanjana.basu2024@vitstudent.ac.in": true,
  "sarada.a2024@vitstudent.ac.in": true,
  "shahana.2024@vitstudent.ac.in": true,
  "shambhavi.paygude2022@vitstudent.ac.in": true,
  "shaurya.garg2023@vitstudent.ac.in": true,
  "shaurya.rawat2023@vitstudent.ac.in": true,
  "shreyas.mishra2022@vitstudent.ac.in": true,
  "snigdha.priya2024@vitstudent.ac.in": true,
  "somyadeep.tarat2024@vitstudent.ac.in": true,
  "sree.rajmuthaiyaal2024@vitstudent.ac.in": true,
  "ssanvee.vijay2024@vitstudent.ac.in": true,
  "sudiksha.kathuria2024@vitstudent.ac.in": true,
  "sunny.gogoi2022@vitstudent.ac.in": true,
  "supratim.ghose2022@vitstudent.ac.in": true,
  "surekakrishika@gmail.com": true,
  "swayam.srivastava2024@vitstudent.ac.in": true,
  "tanush.pratik2022@vitstudent.ac.in": true,
  "tarunram.p2024@vitstudent.ac.in": true,
  "technicaldirector.acmvit@gmail.com": true,
  "vansh.dhir2023@vitstudent.ac.in": true,
  "vansh05dhir@gmail.com": true,
  "vian.mangal2024@vitstudent.ac.in": true,
  "vimalaadhityan.2024@vitstudent.ac.in": true,
  "yasha.pacholee2022@vitstudent.ac.in": true,
  "yash.hirani2023@vitstudent.ac.in": true,
  "yashhirani.0055@gmail.com": true,
  "yashraj.singh2022a@vitstudent.ac.in": true,
  "yusra.rehman2024@vitstudent.ac.in": true,
};

export const normalizeGhostModeEmail = (
	value: string | null | undefined,
): string | undefined => {
	const normalized = value?.trim().toLowerCase();
	return normalized || undefined;
};

export const canUseGhostMode = (email: string | null | undefined): boolean => {
	const normalizedEmail = normalizeGhostModeEmail(email);
	return Boolean(normalizedEmail && GHOST_MODE_EMAILS[normalizedEmail]);
};
