[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:browser-desktop]
command=/opt/scripts/start.sh
environment=DISPLAY=":99",HOME="/home/browser",XDG_RUNTIME_DIR="/tmp/pulse",PULSE_SERVER="unix:/tmp/pulse/native"
autorestart=true
priority=100
user=browser
startsecs=3
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:browser-audio]
command=/opt/scripts/start-audio.sh
environment=DISPLAY=":99",HOME="/home/browser",XDG_RUNTIME_DIR="/tmp/pulse",PULSE_SERVER="unix:/tmp/pulse/native"
autorestart=true
priority=150
user=browser
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:browser-video]
command=/opt/scripts/start-video.sh
environment=DISPLAY=":99"
autorestart=true
priority=160
user=browser
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
