//
//  SfuEvents.swift
//  Conclave
//
//  GENERATED — do not edit by hand.
//  Source of truth: packages/meeting-core/src/sfu-events.ts
//  Regenerate:      node packages/meeting-core/scripts/gen-swift-events.mjs
//
//  These raw values are the exact socket.io event names the SFU server speaks,
//  identical to what the web client uses, so iOS/Android can never drift.
//

/// Built-in socket.io lifecycle events.
enum SfuSystemEvent: String {
    case connect = "connect"
    case disconnect = "disconnect"
    case connectError = "connect_error"
    case reconnect = "reconnect"
}

/// Client → server: requests, commands, and acknowledged RPCs.
enum SfuClientEvent: String {
    case joinRoom = "joinRoom"
    case getRouterRtpCapabilities = "getRouterRtpCapabilities"
    case createProducerTransport = "createProducerTransport"
    case createConsumerTransport = "createConsumerTransport"
    case connectProducerTransport = "connectProducerTransport"
    case connectConsumerTransport = "connectConsumerTransport"
    case produce = "produce"
    case consume = "consume"
    case resumeConsumer = "resumeConsumer"
    case setConsumerPreferences = "setConsumerPreferences"
    case setConsumerPreferencesBatch = "setConsumerPreferencesBatch"
    case closeConsumer = "closeConsumer"
    case closeProducer = "closeProducer"
    case getProducers = "getProducers"
    case restartIce = "restartIce"
    case toggleMute = "toggleMute"
    case toggleCamera = "toggleCamera"
    case closeRemoteProducer = "closeRemoteProducer"
    case closeAllVideo = "closeAllVideo"
    case sendChat = "sendChat"
    case chatImageUploadAuthorize = "chat:imageUploadAuthorize"
    case conclaveAuthorize = "conclave:authorize"
    case conclaveAnswer = "conclaveAnswer"
    case sendReaction = "sendReaction"
    case setHandRaised = "setHandRaised"
    case updateDisplayName = "updateDisplayName"
    case getRooms = "getRooms"
    case lockRoom = "lockRoom"
    case lockChat = "lockChat"
    case setNoGuests = "setNoGuests"
    case setDmEnabled = "setDmEnabled"
    case setImageAttachmentsEnabled = "setImageAttachmentsEnabled"
    case setTtsDisabled = "setTtsDisabled"
    case getRoomLockStatus = "getRoomLockStatus"
    case getChatLockStatus = "getChatLockStatus"
    case getDmEnabledStatus = "getDmEnabledStatus"
    case getTtsDisabledStatus = "getTtsDisabledStatus"
    case setReactionsDisabled = "setReactionsDisabled"
    case getReactionsDisabledStatus = "getReactionsDisabledStatus"
    case admitUser = "admitUser"
    case rejectUser = "rejectUser"
    case kickUser = "kickUser"
    case promoteHost = "promoteHost"
    case redirectUser = "redirectUser"
    case muteAll = "muteAll"
    case browserLaunch = "browser:launch"
    case browserNavigate = "browser:navigate"
    case browserClose = "browser:close"
    case browserGetState = "browser:getState"
    case browserActivity = "browser:activity"
    case appsOpen = "apps:open"
    case appsClose = "apps:close"
    case appsLock = "apps:lock"
    case appsGetState = "apps:getState"
    case appsYjsSync = "apps:yjs:sync"
    case appsYjsUpdate = "apps:yjs:update"
    case appsAwareness = "apps:awareness"
    case gameList = "game:list"
    case gameStart = "game:start"
    case gameMove = "game:move"
    case gameEnd = "game:end"
    case gameGetState = "game:getState"
    case gameJoin = "game:join"
    case gameVoteOpen = "game:vote:open"
    case gameVoteCast = "game:vote:cast"
    case gameVoteCancel = "game:vote:cancel"
    case transcriptGetToken = "transcript:getToken"
    case transcriptSfuRelayStatus = "transcript:sfuRelayStatus"
    case transcriptSfuRelayStart = "transcript:sfuRelayStart"
    case transcriptSfuRelayStop = "transcript:sfuRelayStop"
    case meetingGetConfig = "meeting:getConfig"
    case meetingUpdateConfig = "meeting:updateConfig"
    case webinarGetConfig = "webinar:getConfig"
    case webinarUpdateConfig = "webinar:updateConfig"
    case webinarGenerateLink = "webinar:generateLink"
    case webinarRotateLink = "webinar:rotateLink"
    case adminAdmitAllPending = "admin:admitAllPending"
    case adminRejectAllPending = "admin:rejectAllPending"
    case adminBroadcastNotice = "admin:broadcastNotice"
    case adminClearRaisedHands = "admin:clearRaisedHands"
    case adminCloseUserVideo = "admin:closeUserVideo"
    case adminCloseUserMedia = "admin:closeUserMedia"
    case adminGetAccessLists = "admin:getAccessLists"
    case adminGetParticipants = "admin:getParticipants"
    case adminGetPendingUsers = "admin:getPendingUsers"
    case adminGetRoomsDetailed = "admin:getRoomsDetailed"
    case adminGetRoomState = "admin:getRoomState"
    case adminMuteUser = "admin:muteUser"
    case adminMuteUserAudio = "admin:muteUserAudio"
    case adminStopAllScreenShare = "admin:stopAllScreenShare"
    case adminStopUserScreenShare = "admin:stopUserScreenShare"
    case adminTransferHost = "admin:transferHost"
    case adminAllowUsers = "admin:allowUsers"
    case adminBlockUsers = "admin:blockUsers"
    case adminUnblockUsers = "admin:unblockUsers"
    case adminRevokeAllowedUsers = "admin:revokeAllowedUsers"
    case adminSetPolicies = "admin:setPolicies"
    case adminCloseRoom = "admin:closeRoom"
    case adminEndRoom = "admin:endRoom"
}

/// Server → client: notifications and broadcast state.
enum SfuServerEvent: String {
    case joinApproved = "joinApproved"
    case joinRejected = "joinRejected"
    case userRequestedJoin = "userRequestedJoin"
    case userAdmitted = "userAdmitted"
    case userRejected = "userRejected"
    case userJoined = "userJoined"
    case userLeft = "userLeft"
    case pendingUsersSnapshot = "pendingUsersSnapshot"
    case pendingUserLeft = "pendingUserLeft"
    case waitingRoomStatus = "waitingRoomStatus"
    case newProducer = "newProducer"
    case producerClosed = "producerClosed"
    case participantMuted = "participantMuted"
    case participantCameraOff = "participantCameraOff"
    case participantConnectionState = "participantConnectionState"
    case setVideoQuality = "setVideoQuality"
    case consumerTelemetry = "consumerTelemetry"
    case chatMessage = "chatMessage"
    case conclaveMessage = "conclaveMessage"
    case chatHistorySnapshot = "chatHistorySnapshot"
    case reaction = "reaction"
    case handRaised = "handRaised"
    case handRaisedSnapshot = "handRaisedSnapshot"
    case displayNameUpdated = "displayNameUpdated"
    case displayNameSnapshot = "displayNameSnapshot"
    case hostAssigned = "hostAssigned"
    case hostChanged = "hostChanged"
    case roomLockChanged = "roomLockChanged"
    case chatLockChanged = "chatLockChanged"
    case noGuestsChanged = "noGuestsChanged"
    case dmStateChanged = "dmStateChanged"
    case imageAttachmentsStateChanged = "imageAttachmentsStateChanged"
    case ttsDisabledChanged = "ttsDisabledChanged"
    case reactionsDisabledChanged = "reactionsDisabledChanged"
    case kicked = "kicked"
    case roomClosed = "roomClosed"
    case roomEnded = "roomEnded"
    case redirect = "redirect"
    case serverRestarting = "serverRestarting"
    case adminNotice = "adminNotice"
    case adminUsersChanged = "adminUsersChanged"
    case adminMediaEnforced = "admin:mediaEnforced"
    case adminBulkMediaEnforced = "admin:bulkMediaEnforced"
    case adminHandsCleared = "admin:handsCleared"
    case adminProducerClosed = "admin:producerClosed"
    case adminRoomStateChanged = "admin:roomStateChanged"
    case browserState = "browser:state"
    case browserClosed = "browser:closed"
    case appsState = "apps:state"
    case appsYjsUpdate = "apps:yjs:update"
    case appsAwareness = "apps:awareness"
    case gameState = "game:state"
    case gameView = "game:view"
    case gameSnapshot = "game:snapshot"
    case gameEnded = "game:ended"
    case gameVote = "game:vote"
    case webinarFeedChanged = "webinar:feedChanged"
    case webinarParticipantJoined = "webinar:participantJoined"
    case webinarAttendeeCountChanged = "webinar:attendeeCountChanged"
    case meetingConfigChanged = "meeting:configChanged"
    case webinarConfigChanged = "webinar:configChanged"
}
